### ISSUE TITLE
Crash when embedding enchant::Broker inside an other struct

### ISSUE THREAD

**Issue by dmerejkowsky** [patronus-checker/enchant-rs#4]
Steps to reproduce:

```rust
struct Foo {
    dict: enchant::Dict,
}

impl Foo {
    fn new() -> Self {
        let mut broker = enchant::Broker::new();
        let dict = broker.request_dict("en_US").unwrap();
        Self { dict }
    }
}

#[cfg(test)]
mod tests {

    use super::*;

    #[test]
    fn test_foo() {
        let foo_ = Foo::new();
    }
}
```

```
$ cargo test
running 1 test

** (process:33679): WARNING **: 15:12:40.941: 1 dictionaries weren't free'd.

malloc_consolidate(): unaligned fastbin chunk detected
error: test failed, to rerun pass '--lib'
```

I fixed the problem by using code like this:

```rust
struct Foo {
    dict: enchant::Dict,
}

impl Foo {
    pub fn new(broker: &mut enchant::Broker, lang: &str) -> Self {
        let dict = broker.request_dict(lang).unwrap();
        Self{ dict }
    }
}
```

I'm not sure if this something we can fix in the bindings, but maybe it' s worth mentioning in the documentation ?

**Comment by jtojnar** [comment]
Thanks for reporting.

Yeah, the broker is deallocated at the end of `Foo::new` but the `Dict` created by it is still live, hence the warning. What is worse, the `Dict`’s `broker` field will now point to dead memory, which is likely what causes the issue during memory consolidation.

That definitely is not good and we should fix it. One possibility would be using reference counting for the broker (should not even be an API break since the broker fields are private). But I am not actually familiar enough with Rust to tell if it is idiomatic.

**Comment by dmerejkowsky** [comment]
Let's summon @tux3 and see if he can help :)

**Comment by jtojnar** [comment]
I opened #5, which works around the issue using `Rc` but it is super ugly. I suspect more idiomatic solution might be achieved using lifetimes but I have yet to find time to study them.

**Comment by tux3** [comment]
Hello there. I'm not familiar with libenchant, but it looks there's a `Dict` struct that must never outlive the `Broker`? 
I think `Rc` is completely fine (and in general it's often the simplest solution), but here if you want lifetimes it's not too hard to express that in the type system.

First replace the `*mut EnchantBroker` in Dict by `&'broker mut EnchantBroker`. This tells the borrow checker to track the lifetime of the `broker` field and make sure it outlives the `Dict` struct.  
(Also update the impl block since now Dict takes a lifetime parameter.)

```diff
-pub struct Dict {
+pub struct Dict<'broker> {
     dict: *mut EnchantDict,
-    broker: *mut EnchantBroker,
+    broker: &'broker mut EnchantBroker,
     data: DictData,
```

```diff
-impl Drop for Dict {
+impl Drop for Dict<'_> {
     fn drop(&mut self) {
```

Then in `Dict::new` we have to construct it with a real `&mut` instead of a `*mut`, that lets the lifetime information propagate through.
 
```diff
-impl Dict {
-    fn new(dict: *mut EnchantDict, broker: *mut EnchantBroker) -> Self {
+impl<'broker> Dict<'broker> {
+    fn new(dict: *mut EnchantDict, broker: &'broker mut EnchantBroker) -> Self {
         extern "C" fn describe_fn(
```

And the same in places where we call `Dict::new`, we pass it a `&mut` now.

```diff
             } else {
-                Ok(Dict::new(dict, self.broker))
+                Ok(Dict::new(dict, &mut *self.broker))
             }
```

After that the example in this issue won't compile, because `Foo::new` just drops the broker at the end while the `Dict` still has a `&mut` to it.  
A user would have to make sure they keep both alive.  
Alternatively, with `Rc` the Foo example would still work, just with a little bit of runtime cost instead

Hope that helps

**Comment by jtojnar** [comment]
After talking with some people on [Rust Discord](https://discord.com/channels/442252698964721669/443150878111694848/858025471580831805), I have decided to just go with `Rc`.

**Comment by dmerejkowsky** [comment]
Fair enough :) Thanks for the fix!
